### ISSUE TITLE
Getting an error when trying to finalize a bridge transaction from L2 to L1

### ISSUE THREAD

**Issue by valo** [Snapchain/zkValidium-quickstart#14]
Attaching a screenshot of the error. I am using the default config and followed this guide: https://wiki.polygon.technology/docs/cdk/validium/quickstart/

![Screenshot from 2023-10-06 15-05-51](https://github.com/Snapchain/zkValidium-quickstart/assets/47639/cdcd9064-c46a-49a0-8b6e-1360b99a6c00)

**Comment by bap2pecs** [comment]
@valo thanks for submitting the issue. but I will need more detail to help debug this. Things that will be helpful:

1) have you first send a bridge tx to bridge some fund from the L1 to the L2? (You cannot bridge back fund more than what you have previously bridged from L1 to the L2)

2) do you see any containers exited unexpectedly?

3) could you check the container logs to see if there is anything suspicious?

**Comment by virajpatva** [comment]
Getting same error to answer your questions 
1. My first tx was from cdk-validaum (L2) to L1 (Mock - Ethereum) 
2. No container exited 
3. Can you please specify which container to check , I checked zkevm-bridge-service and there were no error over there

**Comment by virajpatva** [comment]
> Getting same error to answer your questions
> 
> 1. My first tx was from cdk-validaum (L2) to L1 (Mock - Ethereum)
> 2. No container exited
> 3. Can you please specify which container to check , I checked zkevm-bridge-service and there were no error over there

I found the issue when I transfered funds from L1 to L2 and finalise the prev tx. I was successfully able to do it , as you mentioned `(You cannot bridge back fund more than what you have previously bridged from L1 to the L2)`.
