### ISSUE TITLE
Bridge UI : Network Error We cannot connect to the Ethereum node

### ISSUE THREAD

**Issue by gptprotocol** [Snapchain/zkValidium-quickstart#19]
I'm trying to connect to the Bridge UI via and it keeps redirecting me to http://localhost:8088/network-error

I'm running this from my Ubuntu Linux Server. Everything else works on the quickstart (Block Explorer)

The page says:
------

Network Error
We cannot connect to the Ethereum node.
It will be operative again soon

------

How can this be fixed?
<img width="1393" alt="Screenshot 2023-11-21 at 10 48 21 PM" src="https://github.com/Snapchain/zkValidium-quickstart/assets/127793459/fc9b297b-e05d-425c-be5f-982733d60516">

**Comment by bap2pecs** [comment]
what do you see in console logs?

**Comment by gptprotocol** [comment]
This is what I'm seeing
<img width="1410" alt="Screenshot 2023-11-23 at 4 29 10 AM" src="https://github.com/Snapchain/zkValidium-quickstart/assets/127793459/28937c9c-47d9-47f5-bba2-631514bfb695">

**Comment by gptprotocol** [comment]
I was able to resolve by changing from COMMON_HOST=localhost  to  COMMON_HOST= <host ip> . I still think it should detect automatically though.
