### ISSUE TITLE
Issue on test.genesis.config.json

### ISSUE THREAD

**Issue by Neoblock8** [Snapchain/zkValidium-quickstart#2]
In genesis file, what is the root hash and how to find the root hash?

"l1Config" : {
		"chainId": 1337,
		"cdkValidiumAddress": "0x0DCd1Bf9A1b36cE34237eEaFef220932846BCD82",
		"maticTokenAddress": "0x5FbDB2315678afecb367f032d93F642f64180aa3",
		"polygonZkEVMGlobalExitRootAddress": "0xB7f8BC63BbcaD18155201308C8f3540b07f84F5e",
    "cdkDataCommitteeContract": "0x2279B7A0a67DB372996a5FaB50D91eAA73d2eBe6"
	},
  "**root**": "0xd88680f1b151dd67518f9aca85161424c0cac61df2f5424a3ddc04ea25adecc7",
  "genesisBlockNumber": 80,

**Comment by lesterli** [comment]
It is generated for the localhost or mock-l1-network deployment script [1_createGenesis.js](https://github.com/Snapchain/cdk-validium-contracts/blob/main/deployment/1_createGenesis.js#L327).
