### ISSUE TITLE
Total Transactions Not Registering on Block Explorer

### ISSUE THREAD

**Issue by gptprotocol** [Snapchain/zkValidium-quickstart#20]
Total Transactions on Block Explorer are 0 and the graph shows 0.

<img width="1418" alt="Screenshot 2023-11-23 at 5 48 09 AM" src="https://github.com/Snapchain/zkValidium-quickstart/assets/127793459/a12d6abf-e6a7-4322-83f4-ac5acb76c327">

Even though there are transactions.
<img width="1339" alt="Screenshot 2023-11-23 at 5 48 44 AM" src="https://github.com/Snapchain/zkValidium-quickstart/assets/127793459/04ff416d-43b0-4638-8852-ec83a8a44075">

**Comment by bap2pecs** [comment]
this is likely due to some blockscout configs. it should show up after a while. do you still see the issue?

**Comment by gptprotocol** [comment]
Okay, I see it now on the right side but the graph on the left hand side doesn't properly reflect.

<img width="1420" alt="Screenshot 2023-11-23 at 11 36 59 AM" src="https://github.com/Snapchain/zkValidium-quickstart/assets/127793459/83e131a0-5951-4223-9dd7-2befe3b18f5b">

**Comment by bap2pecs** [comment]
@gptprotocol I noticed that it's showing Nov 20. so my guess is this is related to the default time zone config in blockscout. give it another day and see whether it updates

**Comment by gptprotocol** [comment]
Okay thank you I will check back in

**Comment by bap2pecs** [comment]
I don't know too much about blockscout. but it's probably due to some TZ configs as I mentioned above

**Comment by gptprotocol** [comment]
It ended up updating after a few hours.
