### ISSUE TITLE
How Can I Make Changes to The Block Explorer UI (Change Logo and Color)

### ISSUE THREAD

**Issue by gptprotocol** [Snapchain/zkValidium-quickstart#21]
I'm using Dev Containers extension in Visual Studio to connect to the explorer l2 container and make ui changes. I want to change the logo and background colors in the CSS to better reflect the brand of our chain. Once I make the changes I don't see them take affect. 

I'm in the assets folder and then run "npm run build" and still nothing.

Maybe I'm missing something but shouldn't it just update in real time?

**Comment by bap2pecs** [comment]
this blockscout version is going to be replaced soon. see the new UI: https://github.com/Snapchain/zkValidium-quickstart/pull/17

I'd recommend looking into blockscout's official docs
