### ISSUE TITLE
Unable to start rpc server

### ISSUE THREAD

**Issue by DavidRomy** [Snapchain/zkValidium-quickstart#22]
![111](https://github.com/Snapchain/zkValidium-quickstart/assets/45255023/67c6b109-f01e-4aa0-a9ea-18c62fd97f80)
After executing the sudo make run command, the rpc service did not start successfully. Why?

**Comment by panitw** [comment]
It seems the docker image `hermeznetwork/cdk-validium-node:develop` does not contains this binary `/app/cdk-validium-node` which is required in the startup command from docker-compose. 

This is what's inside the container

<img width="387" alt="image" src="https://github.com/Snapchain/zkValidium-quickstart/assets/390664/5a219b41-8dce-4960-a0f8-6753dc8912db">

so I guess changing the startup command from `/app/cdk-validium-node` to `/app/zkevm-node` would work. (I haven't tried this though)

**Comment by gr8h** [comment]
I used an earlier image `hermeznetwork/cdk-validium-node:v0.0.2` that has `/app/cdk-validium-node` not sure of the implication of doing so.

**Comment by bap2pecs** [comment]
this is fixed by #28
