### ISSUE TITLE
cdk-validium-node cannot find /app/cdk-validium-node 

### ISSUE THREAD

**Issue by qj0r9j0vc2** [Snapchain/zkValidium-quickstart#24]
When I deploy docker compose, every container using hermeznetwork/cdk-validium-node:develop has downed.

`/bin/sh: /app/cdk-validium-node: not found`

but container using my local image works.

Finally, I found the reason.

![스크린샷 2024-01-04 오후 2 51 50](https://github.com/Snapchain/zkValidium-quickstart/assets/59428479/b6bea7db-64d6-4970-a15d-a140d5d64cdc)

Currently, `hermeznetwork/cdk-validium-node:develop` image uses `/app/zkevm-node`, and the reason of my local container working was my local image were downloaded before few weeks ago.

**Comment by kiwi202202** [comment]
Did you meet this bug after your command fix?  FATAL   cmd/run.go:116  no contract code at given address

Which version of mock-l1-network should I use?

**Comment by qj0r9j0vc2** [comment]
I meet this when I run command `make run`. 
I assume that few times ago, the CMD part of `hermeznetwork/cdk-validium-node:develop` was set as ["/bin/sh" "-c" "/app/cdk-validium-node run"] .
so maybe It(zkValidium-quickstart) could work. but now, it's not.

![스크린샷 2024-01-04 오후 7 45 40](https://github.com/Snapchain/zkValidium-quickstart/assets/59428479/406253f7-9834-4545-bd76-0304f15233f3)
In above, the `CMD` section of `hermeznetwork/cdk-validlium-node:silenceer` that uploaded 3months ago was set as `CMD ["/bin/sh" "-c" "/app/cdk-validium-node run"]`. 
and this main branch was edited 4 months ago.

But, I'm not sure why `CMD` section changed

**Comment by qj0r9j0vc2** [comment]
https://hub.docker.com/layers/hermeznetwork/cdk-validium-node/silencer/images/sha256-9ecbe2d12aa62a55fd5f4745636540bbcedf15baf77c54f28e7f2de484ce2856?context=explore

using `cdk-validium-node:silencer` success.
I think this is the fault of `hermeznetwork/cdk-validium-node@sha256:daff634a6c57414c785b02cd30288ff740837f87a8dc92553dd750dec609d60f`
