### ISSUE TITLE
Setup CDK via Terraform / Kubernetes?

### ISSUE THREAD

**Issue by sahil3Vedi** [Snapchain/zkValidium-quickstart#27]
Hi,
Wanted to know if the team could release setup instructions for a multiple-node CDK setup utliising Terraform / Kubernetes? This would make CDK a lot more useful!
Thanks!

**Comment by bap2pecs** [comment]
Hi,

Thank you for your inquiry. Currently, this quickstart's primary focus is on helping users acquainted with the technology.

While there are no immediate plans to add multiple-node support to the repository, we appreciate your feedback.

If you represent an organization and have production deployment needs, please reach out to us at info@snapchain.dev to discuss your specific requirements further.

Thanks!
