### ISSUE TITLE
Finalize error, see latest comment

### ISSUE THREAD

**Issue by kmurphypolygon** [Snapchain/zkValidium-quickstart#32]
Hello, I am checking the quick start for the docs.

It fails on `sudo make run` where the output is: 

```
~/zkValidium-quickstart$ sudo make run 
WARN[0000] The "BACK_PROXY_PASS" variable is not set. Defaulting to a blank string.
WARN[0000] The "FRONT_PROXY_PASS" variable is not set. Defaulting to a blank string.
WARN[0000] The "STATS_PROXY_PASS" variable is not set. Defaulting to a blank string.
WARN[0000] The "BACK_PROXY_PASS" variable is not set. Defaulting to a blank string.
WARN[0000] The "FRONT_PROXY_PASS" variable is not set. Defaulting to a blank string.
WARN[0000] The "STATS_PROXY_PASS" variable is not set. Defaulting to a blank string.
WARN[0000] The "BACK_PROXY_PASS" variable is not set. Defaulting to a blank string.
WARN[0000] The "FRONT_PROXY_PASS" variable is not set. Defaulting to a blank string.
WARN[0000] The "STATS_PROXY_PASS" variable is not set. Defaulting to a blank string.
WARN[0000] a network with name zkevm exists but was not created for project "zkvalidium-quickstart".
Set `external: true` to use an existing network
network zkevm was found but has incorrect label com.docker.compose.network set to "zkevm"
make[1]: *** [Makefile:353: run-db] Error 1
make: *** [Makefile:579: run] Error 2
```

**Comment by akshatkumar45969** [comment]
Remove the existing zkevm docker network and try again.
`docker network rm zkevm`

**Comment by kmurphypolygon** [comment]
Cool, thanks <3

**Comment by kmurphypolygon** [comment]
Hi, so the transfer never completes. It's just pending. Is a long wait expected behaviour? If so, how long should I wait ...?

**Comment by bap2pecs** [comment]
@kmurphypolygon are you talking about a bridge tx from L1 to L2? can you provide more context?

**Comment by kmurphypolygon** [comment]
Yeah, sorry, this section of docs: https://docs.polygon.technology/cdk/get-started/quickstart-validium/#4-add-the-network-to-a-web3-wallet the transfer part ... 
I thought everything was running ok, although when I look in the logs I see `dac-setup-committee` Exit 0, and also `zkevm-approve` Exit 0, everything else Up

**Comment by bap2pecs** [comment]
@kmurphypolygon those two Exit 0 are expected. is the transfer on L1 or L2?

**Comment by bap2pecs** [comment]
oh I might know what's going on. it's likely the nonce was incorrectly set in your transfer.

you probably tried a few times and that means you need to go to your Metamask's accounts' settings and clear the nonce:

<img width="345" alt="image" src="https://github.com/Snapchain/zkValidium-quickstart/assets/111917526/48ba8b1b-8ca9-4efc-a278-3c8b100643cb">

**Comment by kmurphypolygon** [comment]
@bap2pecs thanks, you know, when i did this before in december i thought that was the problem, I'm gonna add this to the doc too ... i'll let you know if it works tho.. back soon

**Comment by kmurphypolygon** [comment]
Addition to the docs: "Every time you do `sudo make run` you will also need to reset the nonce in MetaMask" -> does that more or less cover it @bap2pecs ?

**Comment by bap2pecs** [comment]
@kmurphypolygon not necessary. the issue is not related to `make run`. how about the following? (polished with chatGPT)

=====

Note: Troubleshooting Stuck Transactions with Metamask

If you encounter a situation where a transaction made through Metamask appears to be stuck for an extended period of time, it is likely due to an incorrect nonce setting. To resolve this issue, follow the steps below:

1. Open Metamask and navigate to your account.
2. Click on "Settings."
3. In the "Settings" menu, select "Advanced."
4. Locate the option "Clear activity and nonce data" and click on it.

By performing these steps, you will reset the nonce data associated with your account, which can often resolve transaction-related issues. After clearing the activity and nonce data, try initiating the transaction again.

**Comment by kmurphypolygon** [comment]
Works, thank you. I'll just test L1 L2, then close if all OK ...

**Comment by bap2pecs** [comment]
hmm. that's weird. could you try from the scratch? (i.e. also removing the account from MM)

also, the explorer ports need to be updated in the doc as well

4000 -> 80
4001 -> 81

to display the new blockscount UI like this:

![image](https://github.com/Snapchain/zkValidium-quickstart/assets/111917526/1372a319-0bb0-4777-943c-0dba56e7db93)

so http://localhost:4000 should become http://localhost; http://localhost:4000 should become http://localhost:81

**Comment by kmurphypolygon** [comment]
Oh wait, it went through! It just took a while. OK, block explorer not working, i'll check these settings ...

**Comment by bap2pecs** [comment]
hmm, the one ports should still work (see #31), just displaying old UIs

**Comment by kmurphypolygon** [comment]
Yes, it's good, I had it set up from before so it was incorrect ... checking L1/L2 now.

**Comment by kmurphypolygon** [comment]
So L1/L2 looks like it's working but the pics need updating so I'm not sure what the instruction is referring to...

**Comment by bap2pecs** [comment]
do you have a PR for updating the docs? I can jump in collaborate on it

**Comment by kmurphypolygon** [comment]
@bap2pecs it's only a few tiny things, and I haven't pushed it yet ... so don't worry ... there's just an extra verification step but i added a note, L1 good, checking L2 now ..

**Comment by kmurphypolygon** [comment]
@bap2pecs bridging looks ok, but very slow, both txs pending, is that expected?

**Comment by bap2pecs** [comment]
how long were they pending? what kind of difference? could you add some screenshots?

**Comment by kmurphypolygon** [comment]
Here's the PR @bap2pecs: https://github.com/0xPolygon/polygon-docs/pull/158

**Comment by bap2pecs** [comment]
where did you see this jsonrpc error?

**Comment by kmurphypolygon** [comment]
```
Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted", method="estimateGas", transaction={"from":"0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266","to":"0x4C739372258826995C302CD655beE12689B97d3F","data":"0x2cffd02e0000000000000000000000000000000000000000000000000000000000000000ad3228b676f7d3cd4284a5443f17f1962b36e491b30a40b2405849e597ba5fb5b4c11951957c6f8f642c4af61cd6b24640fec6dc7fc607ee8206a99e92410d3021ddb9a356815c3fac1026b6dec5df3124afbadb485c9ba5a3e3398a04b7ba85e58769b32a1beaf1ea27375a44095a0d1fb664ce2dd358e7fcbfb78c26a193440eb01ebfc9ed27500cd4dfc979272d1f0913cc9f66540d7e8005811109e1cf2d887c22bd8750d34016ac3c66b5ff102dacdd73f6b014e710b51e8022af9a1968ffd70157e48063fc33c97a050f7f640233bf646cc98d9524c6b92bcf3ab56f839867cc5f7f196b93bae1e27e6320742445d290f2263827498b54fec539f756afcefad4e508c098b9a7e1d8feb19955fb02ba9675585078710969d3440f5054e0f9dc3e7fe016e050eff260334f18a5d4fe391d82092319f5964f2e2eb7c1c3a5f8b13a49e282f609c317a833fb8d976d11517c571d1221a265d25af778ecf8923490c6ceeb450aecdc82e28293031d10c7d73bf85e57bf041a97360aa2c5d99cc1df82d9c4b87413eae2ef048f94b4d3554cea73d92b0f7af96e0271c691e2bb5c67add7c6caf302256adedf7ab114da0acfe870d449a3a489f781d659e8beccda7bce9f4e8618b6bd2f4132ce798cdc7a60e7e1460a7299e3c6342a579626d22733e50f526ec2fa19a22b31e8ed50f23cd1fdf94c9154ed3a7609a2f1ff981fe1d3b5c807b281e4683cc6d6315cf95b9ade8641defcb32372f1c126e398ef7a5a2dce0a8a7f68bb74560f8f71837c2c2ebbcbf7fffb42ae1896f13f7c7479a0b46a28b6f55540f89444f63de0378e3d121be09e06cc9ded1c20e65876d36aa0c65e9645644786b620e2dd2ad648ddfcbf4a7e5b1a3a4ecfe7f64667a3f0b7e2f4418588ed35a2458cffeb39b93d26f18d2ab13bdce6aee58e7b99359ec2dfd95a9c16dc00d6ef18b7933a6f8dc65ccb55667138776f7dea101070dc8796e3774df84f40ae0c8229d0d6069e5c8f39a7c299677a09d367fc7b05e3bc380ee652cdc72595f74c7b1043d0e1ffbab734648c838dfb0527d971b602bc216c9619ef0abf5ac974a1ed57f4050aa510dd9c74f508277b39d7973bb2dfccc5eeb0618db8cd74046ff337f0a7bf2c8e03e10f642c1886798d71806ab1e888d9e5ee87d0838c5655cb21c6cb83313b5a631175dff4963772cce9108188b34ac87c81c41e662ee4dd2dd7b2bc707961b1e646c4047669dcb6584f0d8d770daf5d7e7deb2e388ab20e2573d171a88108e79d820e98f26c0b84aa8b2f4aa4968dbb818ea32293237c50ba75ee485f4c22adf2f741400bdf8d6a9cc7df7ecae576221665d7358448818bb4ae4562849e949e17ac16e0be16688e156b5cf15e098c627c0056a9000000000000000000000000000000000000000000000000000000000000000074ef06b0008a7343e2c46569fa27a71a1e5f1070d1b92fdb5a20cfcc4629d0177191157da84fb53b5853a8d004dbae935b6715c01e7688d040197bac150b6f0e000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb9226600000000000000000000000000000000000000000000003635c9adc5dea0000000000000000000000000000000000000000000000000000000000000000005200000000000000000000000000000000000000000000000000000000000000000","accessList":null}, error={"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":3,"message":"execution reverted","data":"0x6747a288","cause":null}}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)
    makeError index.js:224
    throwError index.js:233
    $w json-rpc-provider.js:76
    perform json-rpc-provider.js:575
json-rpc-provider.js:6
```
![Screenshot from 2024-01-17 15-58-52](https://github.com/Snapchain/zkValidium-quickstart/assets/149679879/30423f0d-9ece-43c0-8f5d-ba5acba60e60)
![Screenshot from 2024-01-17 15-59-03](https://github.com/Snapchain/zkValidium-quickstart/assets/149679879/a6c3c3a2-63de-4488-b052-dbefe6514420)

**Comment by bap2pecs** [comment]
ah it looks like you are bridging back fund more than you have bridged from L1 to L2

see https://docs.polygon.technology/cdk/get-started/quickstart-validium/#52-l2-to-l1, I put a note:

> You cannot bridge back fund more than what you have previously bridged from L1 to the L2.

**Comment by kmurphypolygon** [comment]
perfect, thank you, i think it's all good then  ... feel free to make any updates to the doc directly whenever you need to by forking, and reach out anytime to me: kmurphy@polygon.technology 
Feel free to close <3
