### ISSUE TITLE
How to setup CDK for custom L1s?

### ISSUE THREAD

**Issue by sahil3Vedi** [Snapchain/zkValidium-quickstart#40]
Hi, is there any tutorial for cases where we'd like to use CDK on top of a custom L1 instead of the local geth node? Any public resources would be appreciated, thanks!

**Comment by bap2pecs** [comment]
@sahil3Vedi I'd recommend check out https://github.com/0xPolygonHermez/zkevm-contracts/tree/develop/deployment/v2. but keep in mind that the Etrog release is just out and might need some time to get stable.

but this is also something we offer to our paid clients. we at Snapchain is a rollup-as-a-service (RaaS) company to help people launch and manage their own CDK chains.

could you share more context about what you are trying to build? feel free to email us at info@snapchain.dev
