### ISSUE TITLE
[blockscout] the confirmation status does not change

### ISSUE THREAD

**Issue by JacksonRGB** [Snapchain/zkValidium-quickstart#44]
Hello, I have a question about Blockscout and Validium. I am running a test network for Validium, but when I run Blockscout (production-zkevm branch), the confirmation status in transaction details always remains 'confirmed by sequencer' and does not change to 'l1 confirmed'. I would like to know if there is a need to set any environment variables for this.

<img width="967" alt="image" src="https://github.com/Snapchain/zkValidium-quickstart/assets/39642866/63262d33-0a6b-4603-8bab-8e6d5086b82b">

**Comment by bap2pecs** [comment]
hi @JacksonRGB, yes that's expected because the quickstart uses a mock prover so the transactions will never reach "l1 confirmed" status.

setting up a real prover is outside the scope of this quickstart

**Comment by bap2pecs** [comment]
@JacksonRGB are you representing an organization? we are a team dedicated to help people set up their own CDK chains in production. if you are interested, please provide some context of you project to info@snapchain.dev
