### ISSUE TITLE
"Real" non-mock Prover config

### ISSUE THREAD

**Issue by hatemosphere** [Snapchain/zkValidium-quickstart#8]
hey guys. big thanks for providing an easy way to spin off Validium for testing purposes! i was just wondering what exactly needs to be changed in Prover config.json so it can produce real proofs? i was trying to figure this out from https://wiki.polygon.technology/docs/zkevm/step5-fullzkevm/, but it seems like it also suggests using some mock config variant.

thanks in advance!

**Comment by githubdoramon** [comment]
Also interested in the above

**Comment by lancelaii** [comment]
did you guys found an answer for this?

**Comment by bap2pecs** [comment]
hey guys, sorry for the late reply. this guide is not supposed to be used for a production environment.

but I put some answers that might be relevant in https://github.com/Snapchain/zkValidium-quickstart/issues/18#issuecomment-1822853172
